[package]
name = "rs-graphs"
version = "0.1.1"
edition = "2021"
authors = ["Guo Fei <me@guofei.site>"]
description = "Graph algorithms in Rust"
license = "MIT"


[dependencies]


[lib]
name = "rs_graphs"
path = "src/lib.rs"